# Generated by Django 4.1.3 on 2022-11-30 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subs', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.PositiveIntegerField(blank=True, default=0)),
                ('avatar', models.TextField(blank=True, default='')),
                ('credit_card', models.CharField(blank=True, default=None, max_length=200)),
                ('payment_history', models.TextField(blank=True, default='', null=True)),
                ('class_history', models.TextField(blank=True, default='', null=True)),
                ('classes', models.ManyToManyField(blank=True, default=None, to='places.class')),
                ('subscription', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='subs.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
